// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package server

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type Server struct {
	ID        pgtype.UUID
	IpAddress *netip.Prefix
	ApiKey    pgtype.UUID
	CreatedAt pgtype.Timestamp
	LastPing  pgtype.Timestamp
}
